export const QUERY_KEYS = {
  GET_BALANCE: "GET_BALANCE",
  GET_TRANSACTION_HISTORY: "GET_TRANSACTION_HISTORY",
  GET_SUI_VALUE: "GET_SUI_VALUE",
  GET_SUBSCRIPTIONS: "GET_SUBSCRIPTIONS",
  GET_PRODUCT_DETAILS: "GET_PRODUCT_DETAILS",
  GET_PRODUCTS: "GET_PRODUCTS",
} as const;
